// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stem.Data.Models;

public partial class Customer
{
    public string UserId { get; set; }

    public DateOnly? RegistrationDate { get; set; }

    public int? LoyaltyPoints { get; set; }

    public virtual User User { get; set; }
}