// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stem.Data.Models;

public partial class RefreshToken
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public DateTime ExperationTime { get; set; }

    public virtual User User { get; set; }
}