// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stem.Data.Models;

public partial class UserPermission
{
    public int UserPermissionId { get; set; }

    public string UserId { get; set; }

    public int? PermissionId { get; set; }

    public string AssignedBy { get; set; }

    public virtual Permission Permission { get; set; }
}