// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Stem.Data.Models;

public partial class Refund
{
    public int RefundId { get; set; }

    public int? InvoiceId { get; set; }

    public decimal? RefundAmount { get; set; }

    public DateOnly? RefundDate { get; set; }

    public string RefundReason { get; set; }

    public virtual Invoice Invoice { get; set; }
}